name: Main

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Prepare
        run: pnpm ci
      - name: Lint
        run: pnpm run check
      - name: Test
        run: pnpm run test -- --coverage
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: pnpm run build
